; Copied from vrtmrz/obsidian-livesync docker/config/livesync.ini
; Upstream commit: bc41355a740335172c9ca08dad6222f5e79698a8

[couchdb]
max_document_size = 50000000

[chttpd]
bind_address = 0.0.0.0
port = 5984
max_http_request_size = 4294967296

[httpd]
WWW-Authenticate = Basic realm="couchdb"

[cors]
credentials = true
origins = app://obsidian.md,capacitor://localhost,http://localhost

[log]
level = warning

