- name: Master node setup
  hosts: master
  become: true
  roles:
    - certbot
    - remnawave_master
    - role: remnashop
      when: enable_remnashop | bool
    - adguard_home
    - role: nginx
      when: enable_nginx | bool
    - role: monitoring
      when: enable_monitoring | bool
    - role: backups
      when: enable_backups | bool
