- name: Master node setup
  hosts: master
  become: true
  roles:
    - certbot
    - role: remnashop
      when: enable_remnashop | bool
    - role: remnawave_panel
      when: enable_remnawave_panel | default(false) | bool
    - role: remnawave_node
      when: enable_remnawave_node | default(false) | bool
    - role: monitoring_agent
      when: enable_monitoring | bool
    - adguard_home
    - role: nginx
      when: enable_nginx | bool
    - role: monitoring
      when: enable_monitoring | bool
    - role: backups
      when: enable_backups | bool
