version: "3.5"
services:
  nodejs-server:
    image: "cnstbmb/khimenkov-nodejs-server:latest"
    restart: always
    container_name: nodejs-server
    networks:
      - app-network
    volumes:
    - configs:/home/app/server/configs/
  angular-app:
    image: "cnstbmb/khimenkov-angular-app:latest"
    restart: always
    container_name: angular-app
    ports:
      - "80:8080"
    networks:
      - app-network
    depends_on:
      - nodejs-server
  postgres-db:
    image: postgres:14-alpine
    restart: always
    container_name: postgres-db
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - app-network
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - nodejs-server
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email cnstbmb@gmail.com --agree-tos --no-eff-email --force-renewal -d himenkov.ru -d www.himenkov.ru
volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /srv/views
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /srv/dhparam/
      o: bind
  pg-data:
    driver: local
    driver_opts:
      type: none
      device: /srv/postgres
      o: bind
networks:
  app-network:
    driver: bridge